[package]
name = "inf492"
version = "0.1.0"
authors = ["Lucas de Ãvila Martins <lucas.a.martins@ufv.br>"]

[dependencies]
lazy_static = "1.1.0"
regex = "1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
rand = "0.5"


[[bin]]
name = "inf492"
path = "src/main.rs"
